# -*- coding: utf-8 -*-
"""Advanced Portfolio Optimization with LSTMs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OwUZosrwj-FT52e0dpra-JynMk2LqFSI
"""

!pip install yfinance

!pip install tensorflow

import numpy as np
import pandas as pd
import plotly.graph_objects as go
import matplotlib.pyplot as plt
import seaborn as sns
import yfinance as yf
from scipy.optimize import minimize
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_absolute_error, mean_squared_error
# Time Series   Analysis

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM, Dropout
from tensorflow.keras.callbacks import EarlyStopping

tickers = ['AAPL', 'MSFT', 'TSLA', 'AMZN','NVDA', 'GOOG','SPY','XLK','QQQ','GLD']

data = yf.download(tickers, start='2020-01-05',end = '2025-01-05')

prices = data['Close'].dropna(how='all')

prices

prices.plot(figsize=(14,7))

returns = ((prices / prices.shift(1)) - 1)
# to calulcate percentage of each day change in prices
returns

annual_returns = returns.mean() * 251 * 100 # annual percentages
annual_returns.values.sort()
annual_returns

annual_returns.plot(kind="bar",figsize=(12,7))
plt.title('Annual Returns')
plt.ylabel('Expected Annual Returns %')
plt.show()

num_assets = len(tickers)
num_assets

weights = np.random.random(num_assets)
weights /= np.sum(weights) #normalized
weights      # generating random weights to represent proportion of investment

# Mean Annual Returns (with random weights)

mean_annual_returns = np.sum(annual_returns * weights)

mean_annual_returns # how annually currently your portfolio will return right now

"""The code calculates how much the portfolio's returns are expected to fluctuate based on the individual assets' volatilities and how they are correlated with each other, considering the proportion of each asset in the portfolio (weights). The result is a measure of the portfolio's risk, with a higher value indicating higher risk."""

# Annual Volatility Covariance understand relationship between assets(Standard Deviation)

np.sqrt(np.dot(weights.T,np.dot(returns.cov() * 251   , weights )))

corr_matrix = returns.corr()
sns.heatmap(corr_matrix , annot=True)

returns[['QQQ','XLK']].plot.scatter(x='QQQ',y='XLK', alpha=0.5)
plt.title('Pairwise Correlation: QQQ vs XLK')
plt.show()

returns[['GLD','NVDA']].plot.scatter(x='GLD',y='NVDA', alpha = 0.5)
plt.title('Pairwise Correlation: GLD vs NVDA')
plt.show

"""Feature Engineering

fit():
Just calculates the stats needed to scale:

For MinMaxScaler: finds min and max

For StandardScaler: finds mean and std deviation

transform():
Uses the stats from .fit() to actually scale the data.
"""

def Scale_data_set(data):

  dataset = data.values
  # Get the number of rows to train the model on
  training_data_len = int(np.ceil( len(dataset) * .8 ))   # np.ceil  is used to convert decimal to whole numbers.

  scaler = MinMaxScaler(feature_range=(0,1))   # scales your fixed feature by default by 0 & 1
  scaled_data = scaler.fit_transform(dataset)
  return training_data_len, scaled_data, dataset, scaler

"""Prepare the data for LSTM

This loop is building sliding windows of 60 past time steps to predict the next time step.

In time series forecasting, we don't just feed one value at a time — we give the model a sequence of values (say, the last 60 days) and ask it to predict the next one (the 61st day).
"""

def Creating_training_data(training_data_len, scaled_data):

  train_data = scaled_data[0:int(training_data_len), :]

  x_train = []
  y_train = []

  for i in range(60, len(train_data)):   # In time series forecasting, previous time steps are often good predictors for the next time step. Here, a window of 60 time steps is used to predict the value at the next time step. This sliding window approach creates many training examples from a single series.
      x_train.append(train_data[i-60:i, 0])
      y_train.append(train_data[i, 0])



  x_train, y_train = np.array(x_train), np.array(y_train) #3 dimensional structure


  x_train = np.reshape(x_train, (x_train.shape[0], x_train.shape[1], 1))


  return x_train, y_train

"""units=50 → 50 LSTM cells (a decent size to learn patterns)

return_sequences=True → needed because we’re stacking another LSTM layer after this

input_shape=(look_back, 1) → input = 60 time steps, 1 feature at each step

🧠 Think of this layer as: "Hey model, here’s a 60-day sequence of one value per day."


"""

def LSTM_model(x_train, y_train, look_back):

  # Build the LSTM model
  model = Sequential()
  model.add(LSTM(units=50, return_sequences=True, input_shape=(look_back, 1)))
  model.add(Dropout(0.2)) # Dropout randomly sets 20% of neurons to 0 during training
  model.add(LSTM(units=50)) #"Summarize the entire input sequence into a single vector, and use it to predict the next day's return."


  model.add(Dropout(0.2))
  model.add(Dense(units=1))  # Output layer for asset returns

  # Compile the model
  model.compile(optimizer='adam', loss='mse')

  # Train the model
  model.fit(x_train, y_train, batch_size=32, epochs=20, validation_split=0.2)

  return model

"""tests a trained LSTM model on unseen data, makes predictions, and returns key evaluation metrics. Let's walk through it step-by-step with clear explanations.


"""

def train_and_validate(model, training_data_len, scaled_data, dataset, scaler):
  # Create the testing data set
  test_data = scaled_data[training_data_len - 60: , :]
  # Create the data sets x_test and y_test
  x_test = []
  y_test = dataset[training_data_len:, :]
  for i in range(60, len(test_data)):
      x_test.append(test_data[i-60:i, 0])

  # Convert the data to a numpy array
  x_test = np.array(x_test)

  # Reshape the data
  x_test = np.reshape(x_test, (x_test.shape[0], x_test.shape[1], 1 ))
    #Reshapes for LSTM input: [samples, timesteps, features]
  # Get the models predicted price values
  predictions = model.predict(x_test)
  predictions = scaler.inverse_transform(predictions)

  rmse = np.sqrt(mean_squared_error(y_test, predictions))
  mae = mean_absolute_error(y_test, predictions)
  mape = np.mean(np.abs((y_test - predictions) / y_test)) * 100

  return predictions, rmse, mae, mape, y_test
  #| Metric | What it Tells                                               |
#| ------ | ----------------------------------------------------------- |
#| RMSE   | Penalizes large errors (more sensitive than MAE)            |
#| MAE    | Average absolute difference between prediction and actual   |
#| MAPE   | Percent error — how far off the predictions are, relatively |

"""Predicted vs actual prices — which you can use for:

Plotting

Strategy evaluation

Portfolio simulations

STOCK PREDICTION PIPELINE


"""

def Stock_prediction(data, title):
  training_data_len, scaled_data, dataset, scaler = Scale_data_set(data)
  x_train, y_train = Creating_training_data(training_data_len, scaled_data)
  model = LSTM_model(x_train, y_train, 60)
  predictions, rmse, mae, mape, y_test = train_and_validate(model, training_data_len, scaled_data, dataset, scaler)

  return rmse, predictions, mae, mape, y_test

"""designed to visually compare the predicted stock prices from your LSTM model against the actual stock prices."""

def visualize_predictions(predictions, y_test, stock_symbol):
    plt.figure(figsize=(14,7))
    plt.plot(y_test, label=f'{stock_symbol} Actual Prices')
    plt.plot(predictions, label=f'{stock_symbol} Predicted Prices')
    plt.legend()
    plt.title(f"{stock_symbol} Model Predictions vs Actual Prices")
    plt.show()

stock_data = {}
for st in tickers:
  stock_data['{}'.format(st)] = prices.filter([st])

stock_data

"""running your LSTM-based stock prediction pipeline on multiple stock tickers, and for each one, it:

Prepares the data

Trains and tests the LSTM model

Records the prediction errors (RMSE, MAE, MAPE)

Stores predictions for further analysis

Visualizes actual vs predicted stock prices


"""

error_table = {}
predicted_returns_data = {}

for i in tickers:
   DATA = stock_data[i]
   DATA = DATA.rename(columns = {i:"Close"})
   rmse, predictions, mae, mape, y_test = Stock_prediction(DATA, i)
   print("'root mean squared error' of {} = ".format(i) + str(rmse))
   print("'mean absolute error' of {} = ".format(i) + str(mae))
   print("MAPE of {} = ".format(i) + str(mape))
   error_table[i] = (rmse, mae, mape)
   predicted_returns_data[i] = predictions
   visualize_predictions(predictions, y_test, i)

error_table = pd.DataFrame(error_table, index=['RMSE', 'MAE', 'MAPE'])
error_table

"""Converting predicted stock prices into daily percentage returns.

You're transforming price predictions into returns, which is:

More suitable for portfolio allocation, Sharpe ratio, etc.

Easier to compare across different stocks.

Essential for simulating investment performance.
"""

# Convert predicted prices into daily returns
def compute_daily_returns_from_prices(predicted_returns_data):
    predicted_daily_returns = {}

    for stock, predicted_prices in predicted_returns_data.items():
        # Ensure predictions are a 1D array
        predicted_prices = predicted_prices.flatten()

        # Calculate daily returns
        daily_returns = ((predicted_prices[1:] / predicted_prices[:-1]) - 1) * 100

        # Store in dictionary
        predicted_daily_returns[stock] = daily_returns

    return predicted_daily_returns

# Calculate the 6-month moving average for predicted daily returns
def compute_six_month_moving_avg(predicted_daily_returns):
    six_month_moving_avg_returns = {}

    for stock, daily_returns in predicted_daily_returns.items():
        # Convert daily returns to a pandas Series for rolling calculations
        daily_returns_series = pd.Series(daily_returns)

        # Compute the 6-month moving average (126 trading days)
        moving_avg = daily_returns_series.rolling(window=126).mean()

        # Store the last value of the 6-month moving average
        six_month_moving_avg_returns[stock] = moving_avg.iloc[-1]

    return six_month_moving_avg_returns

# Get top-performing stocks
def get_top_performing_stocks(six_month_moving_avg_returns, top_n=5):
    # Sort stocks by their 6-month moving average returns in descending order
    sorted_stocks = sorted(six_month_moving_avg_returns.items(), key=lambda x: x[1], reverse=True)[:top_n]

    # Format the result for display
    print("Top 5 Best-Performing Stocks (6-Month Moving Average of Predicted Daily Returns):")
    for stock, avg_return in sorted_stocks:
        print(f"{stock}: {avg_return:.2f}")

    return sorted_stocks

# Main process
def best_stocks():
    # Step 1: Compute daily returns from predicted prices
    predicted_daily_returns = compute_daily_returns_from_prices(predicted_returns_data)

    # Step 2: Compute the 6-month moving average for daily returns
    six_month_moving_avg_returns = compute_six_month_moving_avg(predicted_daily_returns)

    # Step 3: Get and display the top 5 best-performing stocks
    top_performing_stocks = get_top_performing_stocks(six_month_moving_avg_returns, top_n=5)

    return top_performing_stocks

top_stocks = best_stocks()

assets = []
for i in top_stocks:
  assets.append(i[0])

returns = returns[assets].dropna()
returns

"""Below we begin the process of portfolio optimization for our chosen assets.

First we define a function to calculate the metrics we want to be consideren when optimizing out portfolio, namely: portfolio return, portfolio volatility, and Sharpe Ratio. Portfolio Return is how much the portfolio is expected to make or lose in a given year relative to it's worth. The Portfolio Volatility is the annual risk of the portfolio, which is the uncertainty in expected returns. The Sharpe Ratio is the return of the portfolio associated with the risk. The goal of our optimization is to maximize the Sharpe Ratio, essentially maximizing the reward to risk ratio of our portfolio. We will show the optimal portfolio below, along with it's asset's weights, sharpe ratio, risk, and expected return:

You used SLSQP because:

You have constraints (sum(weights)=1)

You want bounded weights (between 0 and 1)

You are maximizing a complex, smooth function (Sharpe Ratio)

SLSQP is one of the few algorithms in scipy.optimize.minimize that can handle all three conditions elegantly.

This tells you:

What proportion of your total capital should be invested in each asset
(in order to maximize risk-adjusted return)
"""

num_assets = len(assets)
mean_returns = returns.mean() * 252  # Annualized returns
cov_matrix = returns.cov() * 252  # Annualized covariance matrix

# Step 3: Define portfolio performance metrics
def portfolio_performance(weights, mean_returns, cov_matrix, risk_free_rate=0.04):
    weights = np.array(weights)
    portfolio_return = np.dot(weights, mean_returns)
    portfolio_volatility = np.sqrt(np.dot(weights.T, np.dot(cov_matrix, weights)))
    sharpe_ratio = (portfolio_return - risk_free_rate) / portfolio_volatility
    return portfolio_return, portfolio_volatility, sharpe_ratio


# Step 4: Define optimization functions
def negative_sharpe_ratio(weights, mean_returns, cov_matrix, risk_free_rate=0.04):
    _, _, sharpe_ratio = portfolio_performance(weights, mean_returns, cov_matrix, risk_free_rate)
    return -sharpe_ratio  # Negative because we want to maximize the Sharpe ratio

def constraint_sum_weights(weights):
    return np.sum(weights) - 1

# Step 5: Optimize portfolio
num_assets = len(assets)
constraints = ({'type': 'eq', 'fun': constraint_sum_weights})
bounds = tuple((0, 1) for _ in range(num_assets))
initial_weights = num_assets * [1. / num_assets]

optimized_result = minimize(negative_sharpe_ratio, initial_weights, args=(mean_returns, cov_matrix),
                            method='SLSQP', bounds=bounds, constraints=constraints)

optimized_weights = optimized_result.x

# Step 6: Portfolio Performance and Visualization
optimized_return, optimized_volatility, optimized_sharpe = portfolio_performance(
    optimized_weights, mean_returns, cov_matrix)

print("Optimized Portfolio Weights:")
for ticker, weight in zip(assets, optimized_weights):
    print(f"{ticker}: {weight:.2%}")

print("\nOptimized Portfolio Performance:")
print(f"Expected Annual Return: {optimized_return:.2%}")
print(f"Annual Volatility: {optimized_volatility:.2%}")
print(f"Sharpe Ratio: {optimized_sharpe:.2f}")

"""This function calculates the three main portfolio metrics:

Expected Return: np.dot(weights, mean_returns)

Volatility (Standard Deviation): sqrt(wᵀ * Σ * w)

Sharpe Ratio: (Return - Risk-free rate) / Volatility

Since optimizers minimize functions, we negate the Sharpe ratio.

The optimizer will try to minimize the negative Sharpe, i.e., maximize the Sharpe.

And now we can plot the Efficient Frontier. The Efficient Frontier shows all portfolios that offer the maximum return for a given level of risk. We will also plot our optimal portfolio along the efficient frontier:
"""

# Plot Efficient Frontier
def portfolio_volatility(weights, mean_returns, cov_matrix):
    return np.sqrt(np.dot(weights.T, np.dot(cov_matrix, weights)))

def efficient_frontier(mean_returns, cov_matrix, risk_free_rate=0.04):
    frontier_returns = np.linspace(0, max(mean_returns) + 0.04, 100)
    frontier_volatilities = []

    for target_return in frontier_returns:
        constraints = [{'type': 'eq', 'fun': constraint_sum_weights},
                       {'type': 'eq', 'fun': lambda w: np.dot(w, mean_returns) - target_return}]
        result = minimize(portfolio_volatility, initial_weights, args=(mean_returns, cov_matrix),
                          method='SLSQP', bounds=bounds, constraints=constraints)
        if result.success:
            frontier_volatilities.append(result.fun)
        else:
            frontier_volatilities.append(np.nan)

    return frontier_returns, frontier_volatilities

frontier_returns, frontier_volatilities = efficient_frontier(mean_returns, cov_matrix)

fig = go.Figure()

# Efficient Frontier plot
fig.add_trace(go.Scatter(x=frontier_volatilities, y=frontier_returns, mode='lines',
                         name='Efficient Frontier', line=dict(color='blue', width=3)))

# Step 3: Plot Optimal Portfolio (Maximum Sharpe Ratio Portfolio)
optimized_result = minimize(negative_sharpe_ratio, initial_weights, args=(mean_returns, cov_matrix),
                            method='SLSQP', bounds=bounds, constraints=constraints)

optimized_weights = optimized_result.x
optimized_return, optimized_volatility, optimized_sharpe = portfolio_performance(
    optimized_weights, mean_returns, cov_matrix)

# Plot Optimal Portfolio (Maximum Sharpe Ratio Portfolio)
fig.add_trace(go.Scatter(x=[optimized_volatility], y=[optimized_return], mode='markers',
                         name='Optimal Portfolio', marker=dict(color='red', size=10, symbol='star')))

# Step 4: Customize Layout for Interactivity
fig.update_layout(
    title='Efficient Frontier with Optimal Portfolio',
    xaxis_title='Portfolio Volatility %(Std. Dev.)',
    yaxis_title='Portfolio Return %',
    showlegend=True,
    template='plotly_dark',
    hovermode="closest",
    width=800,
    height=600
)

# Show the plot interactively
fig.show()

"""This project successfully demonstrated the integration of Long Short-Term Memory (LSTM) networks with Mean-Variance Optimization (MVO) for portfolio optimization. By leveraging LSTM models to predict asset returns and using moving averages to identify top-performing stocks, the optimized portfolio achieved a Sharpe Ratio of 1.49, an expected annual return of 51.57%, and annual volatility of 32.02%.

The project emphasized the potential of deep learning models in financial decision-making, showcasing the ability of LSTMs to capture temporal patterns in asset prices. The optimization process effectively concentrated weights in high-performing assets such as GLD (39.24%) and NVDA (44.25%), reflecting their superior predicted returns and risk-adjusted performance.

Future Directions

To further enhance this approach, several avenues can be explored:

Experimenting with advanced LSTM architectures (e.g., bidirectional LSTMs or attention mechanisms).

Incorporating larger and more diverse datasets, including additional stocks and longer historical data.

Implementing ensemble learning methods to improve prediction robustness.

Exploring reinforcement learning frameworks for dynamic portfolio rebalancing.

The SLSQP algorithm (Sequential Least Squares Programming) works like this:

Starts with initial weights — say equal distribution across all assets.

Evaluates the Sharpe ratio.

Tweaks the weights slightly to try and improve the Sharpe.

Keeps repeating this iteratively, checking the constraints each time.

Stops when it can't find a better combination — i.e., it has minimized the negative Sharpe.
"""



"""This portfolio_performance function is the core of calculating how well a portfolio is expected to perform.
It takes the portfolio weights (how much is invested in each asset), the mean_returns, and the cov_matrix as inputs.
It calculates and returns three key metrics:
Portfolio Return: The expected overall return of the portfolio.
Portfolio Volatility: A measure of the portfolio's risk or how much its returns are likely to fluctuate.
Sharpe Ratio: A measure of risk-adjusted return, calculated as (portfolio return - risk-free rate) / portfolio volatility. A higher Sharpe ratio generally indicates a better investment.
"""